### ISSUE TITLE
InvalidGitRepositoryError

### ISSUE THREAD

**Issue by mgsteam** [Kavan72/valorant-versioning-script#2]
Getting this error
Using heroku
```
2022-03-01T21:12:06.716039+00:00 app[run.1]: Downloading file ShooterGame/Binaries/Win64/VALORANT-Win64-Shipping.exe...
2022-03-01T21:12:07.276731+00:00 app[run.1]: Traceback (most recent call last):
2022-03-01T21:12:07.276782+00:00 app[run.1]:   File "/app/main.py", line 117, in <module>
2022-03-01T21:12:07.277099+00:00 app[run.1]:     main()
2022-03-01T21:12:07.277115+00:00 app[run.1]:   File "/app/main.py", line 108, in main
2022-03-01T21:12:07.277287+00:00 app[run.1]:     check_update_for_region(configuration)
2022-03-01T21:12:07.277310+00:00 app[run.1]:   File "/app/main.py", line 93, in check_update_for_region
2022-03-01T21:12:07.277457+00:00 app[run.1]:     push_to_github(commit_msg=f"Update version for {region} to {version_data['version']}")
2022-03-01T21:12:07.277488+00:00 app[run.1]:   File "/app/main.py", line 48, in push_to_github
2022-03-01T21:12:07.277631+00:00 app[run.1]:     repo = Repo(REPO_DIR)
2022-03-01T21:12:07.277650+00:00 app[run.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/git/repo/base.py", line 224, in __init__
2022-03-01T21:12:07.277878+00:00 app[run.1]:     self.working_dir: Optional[PathLike] = self._working_tree_dir or self.common_dir
2022-03-01T21:12:07.277892+00:00 app[run.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/git/repo/base.py", line 307, in common_dir
2022-03-01T21:12:07.278124+00:00 app[run.1]:     raise InvalidGitRepositoryError()
2022-03-01T21:12:07.278198+00:00 app[run.1]: git.exc.InvalidGitRepositoryError
```
How can i fix it?

**Comment by Kavan72** [comment]
hey @mgsteam 

did you add these environment variables to your Heroku app?

```
GITHUB_USERNAME = os.environ['GITHUB_USERNAME']
GITHUB_EMAIL = os.environ['GITHUB_EMAIL']
GITHUB_PASSWORD = os.environ['GITHUB_PASSWORD']
GITHUB_REPOSITORY_NAME = os.environ['GITHUB_REPOSITORY_NAME']
```

**Comment by mgsteam** [comment]
yes and I even printed them out to double check.

**Comment by Kavan72** [comment]
did you created blank repo ?

**Comment by mgsteam** [comment]
honestly i don't know what the issue was but i just created another repo and it worked!

**Comment by Kavan72** [comment]
@mgsteam you are right, there is some problem in `ManifestDownloader` and also I've added traceback logging to debug the error.

**Comment by Kavan72** [comment]
#3
